<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerNotificationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\MachineController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductionController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\QuoteController;
use App\Http\Controllers\StoreController;
use App\Http\Controllers\StoreSettingsController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TechnicalSheetController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', [StoreController::class, 'index'])->name('loja.index');
Route::get('loja/produto/{produto}', [StoreController::class, 'product'])->name('loja.product');
Route::get('loja/carrinho', [StoreController::class, 'cart'])->name('loja.cart');
Route::post('loja/produto/{produto}/carrinho', [StoreController::class, 'add'])->name('loja.add');
Route::post('loja/carrinho/{key}/remover', [StoreController::class, 'remove'])->where('key', '.*')->name('loja.remove');
Route::get('loja/finalizar', [StoreController::class, 'checkout'])->name('loja.checkout');
Route::post('loja/finalizar', [StoreController::class, 'placeOrder'])->name('loja.place-order');
Route::get('loja/pedido/{number}/sucesso', [StoreController::class, 'success'])->name('loja.success');
Route::get('loja/rastrear', [StoreController::class, 'trackingForm'])->name('loja.tracking');
Route::post('loja/rastrear', [StoreController::class, 'tracking'])->name('loja.tracking.search');

Route::middleware('guest')->group(function () {
    Route::get('/entrar', [AuthController::class, 'create'])->name('login');
    Route::post('/entrar', [AuthController::class, 'store'])->name('login.store');
});

Route::middleware('auth')->group(function () {
    Route::get('/painel', DashboardController::class)->middleware('access:dashboard')->name('dashboard');
    Route::get('minha-conta', [ProfileController::class, 'edit'])->name('perfil.edit');
    Route::put('minha-conta', [ProfileController::class, 'update'])->name('perfil.update');
    Route::resource('usuarios', UserController::class)->except('show', 'destroy')->middleware('access:users');
    Route::get('administracao/loja', [StoreSettingsController::class, 'edit'])->middleware('access:store_settings')->name('loja.settings.edit');
    Route::put('administracao/loja', [StoreSettingsController::class, 'update'])->middleware('access:store_settings')->name('loja.settings.update');
    Route::resource('clientes', CustomerController::class)->except('show', 'destroy')->middleware('access:customers');
    Route::resource('crm', LeadController::class)->parameters(['crm' => 'lead'])->except('destroy')->middleware('access:crm');
    Route::patch('crm/{lead}/etapa', [LeadController::class, 'changeStage'])->middleware('access:crm')->name('crm.stage');
    Route::post('crm/{lead}/atividades', [LeadController::class, 'addActivity'])->middleware('access:crm')->name('crm.activities.store');
    Route::post('crm/{lead}/converter-cliente', [LeadController::class, 'convertToCustomer'])->middleware('access:crm')->name('crm.convert-customer');
    Route::resource('materiais', MaterialController::class)->except('show', 'destroy')->middleware('access:materials');
    Route::resource('maquinas', MachineController::class)->except('show', 'destroy')->middleware('access:production');
    Route::get('maquinas/{maquina}/manutencoes', [MachineController::class, 'maintenances'])->middleware('access:production')->name('maquinas.maintenances');
    Route::post('maquinas/{maquina}/manutencoes', [MachineController::class, 'storeMaintenance'])->middleware('access:production')->name('maquinas.maintenances.store');
    Route::post('maquinas/{maquina}/manutencoes/{maintenance}/concluir', [MachineController::class, 'completeMaintenance'])->middleware('access:production')->name('maquinas.maintenances.complete');
    Route::resource('fornecedores', SupplierController::class)->except('show', 'destroy')->middleware('access:suppliers');
    Route::get('compras', [PurchaseOrderController::class, 'index'])->middleware('access:purchases')->name('compras.index');
    Route::get('compras/nova', [PurchaseOrderController::class, 'create'])->middleware('access:purchases')->name('compras.create');
    Route::post('compras', [PurchaseOrderController::class, 'store'])->middleware('access:purchases')->name('compras.store');
    Route::get('compras/{compra}', [PurchaseOrderController::class, 'show'])->middleware('access:purchases')->name('compras.show');
    Route::post('compras/{compra}/receber', [PurchaseOrderController::class, 'receive'])->middleware('access:purchases')->name('compras.receive');
    Route::get('financeiro', [FinanceController::class, 'index'])->middleware('access:finance')->name('financeiro.index');
    Route::post('financeiro/{lancamento}/baixar', [FinanceController::class, 'settle'])->middleware('access:finance')->name('financeiro.settle');
    Route::resource('produtos', ProductController::class)->except('show', 'destroy')->middleware('access:products');
    Route::post('produtos/{produto}/fotos', [ProductController::class, 'storeImages'])->middleware('access:products')->name('produtos.images.store');
    Route::delete('produtos/{produto}/fotos/{foto}', [ProductController::class, 'destroyImage'])->middleware('access:products')->name('produtos.images.destroy');
    Route::get('produtos/{produto}/ficha-tecnica', [TechnicalSheetController::class, 'edit'])->middleware('access:products')->name('produtos.technical-sheet.edit');
    Route::put('produtos/{produto}/ficha-tecnica', [TechnicalSheetController::class, 'update'])->middleware('access:products')->name('produtos.technical-sheet.update');
    Route::resource('orcamentos', QuoteController::class)->except('show', 'destroy')->middleware('access:quotes');
    Route::post('orcamentos/{orcamento}/converter-em-pedido', [QuoteController::class, 'convertToOrder'])->middleware('access:quotes')->name('orcamentos.convert');
    Route::get('pedidos', [OrderController::class, 'index'])->middleware('access:orders')->name('pedidos.index');
    Route::get('pedidos/{pedido}', [OrderController::class, 'show'])->middleware('access:orders')->name('pedidos.show');
    Route::post('pedidos/{pedido}/confirmar-entrada', [OrderController::class, 'confirmDeposit'])->middleware('access:orders')->name('pedidos.confirm-deposit');
    Route::post('pedidos/{pedido}/aprovar-arte', [OrderController::class, 'approveArt'])->middleware('access:orders')->name('pedidos.approve-art');
    Route::post('pedidos/{pedido}/criar-op', [OrderController::class, 'createProductionOrder'])->middleware('access:orders')->name('pedidos.create-op');
    Route::post('pedidos/{pedido}/despachar', [OrderController::class, 'ship'])->middleware('access:deliveries')->name('pedidos.ship');
    Route::get('entregas', [DeliveryController::class, 'index'])->middleware('access:deliveries')->name('entregas.index');
    Route::get('notificacoes', [CustomerNotificationController::class, 'index'])->middleware('access:notifications')->name('notificacoes.index');
    Route::post('notificacoes/{notificacao}/marcar-enviada', [CustomerNotificationController::class, 'markSent'])->middleware('access:notifications')->name('notificacoes.mark-sent');
    Route::post('notificacoes/{notificacao}/reabrir', [CustomerNotificationController::class, 'reopen'])->middleware('access:notifications')->name('notificacoes.reopen');
    Route::get('producao', [ProductionController::class, 'index'])->middleware('access:production')->name('producao.index');
    Route::get('producao/{ordemProducao}', [ProductionController::class, 'show'])->middleware('access:production')->name('producao.show');
    Route::post('producao/{ordemProducao}/avancar', [ProductionController::class, 'advance'])->middleware('access:production')->name('producao.advance');
    Route::post('producao/{ordemProducao}/ocorrencia', [ProductionController::class, 'logOccurrence'])->middleware('access:production')->name('producao.occurrence');
    Route::post('/sair', [AuthController::class, 'destroy'])->name('logout');
});
