@extends('layouts.app', ['title' => 'Programa de revenda · Alfarei CNC'])

@section('content')
<div class="heading"><div><p class="eyebrow">CLIENTES · PARCERIAS</p><h1>Programa de revenda</h1><p class="muted">Aprovação humana, preços por quantidade e revisão sem rebaixamento automático.</p></div><a class="secondary" href="{{ route('clientes.index') }}">Ver clientes →</a></div>
<div class="reseller-overview"><article class="panel"><span>Solicitações abertas</span><strong>{{ $applications->total() }}</strong><small>Em análise ou aguardando informação</small></article><article class="panel"><span>Revisões sugeridas</span><strong>{{ $reviews->count() }}</strong><small>Sem atividade ou revisão há 12 meses</small></article></div>
<section class="panel reseller-list"><div class="reseller-list-head"><h2>Solicitações</h2><p>O cliente só recebe preço de revenda depois da aprovação.</p></div><div class="table-panel"><table><thead><tr><th>CLIENTE</th><th>NEGÓCIO</th><th>CANAL</th><th>ENVIADA EM</th><th>STATUS</th><th></th></tr></thead><tbody>@forelse($applications as $application)<tr><td><b>{{ $application->customer->name }}</b><small>{{ $application->customer->email }}</small></td><td>{{ $application->business_name ?: 'Não informado' }}</td><td>{{ ['physical' => 'Loja física', 'online' => 'Loja virtual', 'social' => 'Redes sociais', 'marketplace' => 'Marketplace', 'other' => 'Outro'][$application->sales_channel] ?? $application->sales_channel }}</td><td>{{ $application->created_at->format('d/m/Y') }}</td><td><span class="status {{ $application->status === 'pending' ? 'warn' : 'off' }}">{{ $application->status === 'pending' ? 'Em análise' : 'Aguardando cliente' }}</span></td><td><a class="edit" href="{{ route('revendedores.show', $application) }}">Analisar →</a></td></tr>@empty<tr><td colspan="6" class="empty">Nenhuma solicitação aberta.</td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $applications->links() }}</div></section>
<section class="panel reseller-list"><div class="reseller-list-head"><h2>Revisões sugeridas</h2><p>Uma pausa nas compras não altera o perfil. Registre o contato ou tome uma decisão fundamentada.</p></div><div class="table-panel"><table><thead><tr><th>REVENDEDOR</th><th>REVISÃO DESDE</th><th>CONTATO</th><th></th></tr></thead><tbody>@forelse($reviews as $item)<tr><td><b>{{ $item['customer']->name }}</b><small>{{ $item['customer']->email }}</small></td><td>{{ $item['due_at']->format('d/m/Y') }}</td><td>{{ $item['customer']->phone ?: 'Sem telefone' }}</td><td><a class="edit" href="{{ route('revendedores.customer', $item['customer']) }}">Revisar →</a></td></tr>@empty<tr><td colspan="4" class="empty">Nenhuma revisão pendente.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel reseller-list"><div class="reseller-list-head"><h2>Revendedores ativos</h2><p>Acesse o histórico ou revise um perfil a qualquer momento.</p></div><div class="table-panel"><table><thead><tr><th>REVENDEDOR</th><th>ÚLTIMO PEDIDO</th><th>ÚLTIMA REVISÃO</th><th></th></tr></thead><tbody>@forelse($partners as $partner)<tr><td><b>{{ $partner->name }}</b><small>{{ $partner->email }}</small></td><td>{{ $partner->orders_max_created_at ? \Illuminate\Support\Carbon::parse($partner->orders_max_created_at)->format('d/m/Y') : 'Nenhum' }}</td><td>{{ $partner->reseller_reviewed_at?->format('d/m/Y') ?: 'Não registrada' }}</td><td><a class="edit" href="{{ route('revendedores.customer', $partner) }}">Ver perfil →</a></td></tr>@empty<tr><td colspan="4" class="empty">Nenhum revendedor ativo.</td></tr>@endforelse</tbody></table></div></section>
@endsection
