@extends('layouts.app', ['title' => ($quote->exists ? $quote->number : 'Novo orçamento').' · Alfarei CNC'])
@section('content')
@php($items = old('items', $quote->exists ? $quote->items->map(fn($item) => $item->only(['product_id', 'description', 'type', 'quantity', 'unit_price', 'unit_cost', 'configuration_snapshot']))->all() : [['kind' => 'custom', 'product_id' => '', 'description' => '', 'quantity' => 1, 'unit_price' => 0, 'unit_cost' => 0]]))
<div class="heading"><div><p class="eyebrow">COMERCIAL · {{ $quote->exists ? $quote->number.' · V'.$quote->version : 'NOVO ORÇAMENTO' }}</p><h1>{{ $quote->exists ? 'Editar orçamento' : 'Criar orçamento' }}</h1><p class="muted">Versão comercial com preço, custo, anexos técnicos e aprovação do cliente.</p></div><a class="secondary" href="{{ route('orcamentos.index') }}">← Voltar</a></div>
@if($errors->any())<div class="display-errors" role="alert">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<form class="quote-form" method="POST" action="{{ $quote->exists ? route('orcamentos.update', $quote) : route('orcamentos.store') }}" data-display-price-url="{{ route('orcamentos.display.price') }}">@csrf @if($quote->exists) @method('PUT') @endif
<div class="quote-workspace"><div class="panel quote-editor">
<section class="form-section"><h2>1. Dados comerciais</h2><div class="form-grid"><label class="span-2">Cliente<select name="customer_id" required><option value="">Selecione um cliente</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id', $quote->customer_id) == $customer->id)>{{ $customer->name }}</option>@endforeach</select></label><label>Status<input value="Rascunho" disabled></label><label>Validade<input type="date" name="valid_until" value="{{ old('valid_until', $quote->valid_until?->format('Y-m-d')) }}"></label><label>Entrada (%)<input type="number" min="0" max="100" step="0.01" name="deposit_percent" value="{{ old('deposit_percent', $quote->deposit_percent ?? 50) }}"></label><label>Prazo de produção (dias)<input type="number" min="0" name="production_lead_days" value="{{ old('production_lead_days', $quote->production_lead_days) }}"></label><label>Prazo de entrega/despacho (dias)<input type="number" min="0" name="delivery_lead_days" value="{{ old('delivery_lead_days', $quote->delivery_lead_days) }}"></label></div></section>
<section class="form-section pricing-section"><div class="items-head"><div><h2>2. Precificação avançada</h2><p>Usada para calcular o preço sugerido; não altera itens já negociados.</p></div></div><div class="pricing-grid"><label>Impostos (%)<input class="pricing-input" id="tax_percent" type="number" min="0" max="100" step="0.01" name="tax_percent" value="{{ old('tax_percent', $quote->tax_percent ?? 0) }}"></label><label>Comissão (%)<input class="pricing-input" id="commission_percent" type="number" min="0" max="100" step="0.01" name="commission_percent" value="{{ old('commission_percent', $quote->commission_percent ?? 0) }}"></label><label>Taxas (%)<input class="pricing-input" id="fee_percent" type="number" min="0" max="100" step="0.01" name="fee_percent" value="{{ old('fee_percent', $quote->fee_percent ?? 0) }}"></label><label>Margem-alvo (%)<input class="pricing-input" id="target_margin_percent" type="number" min="0" max="99.99" step="0.01" name="target_margin_percent" value="{{ old('target_margin_percent', $quote->target_margin_percent ?? 20) }}"></label><label>Desconto (%)<input class="pricing-input" id="discountPercent" type="number" min="0" max="100" step="0.01" name="discount_percent" value="{{ old('discount_percent', $quote->discount_percent ?? 0) }}"></label></div></section>
<section class="form-section"><div class="items-head"><div><h2>3. Itens e composição</h2><p>Selecione Display adesivado para informar medidas e calcular automaticamente.</p></div><button class="secondary" type="button" id="addItem">＋ Adicionar item</button></div><div id="quoteItems">@foreach($items as $index=>$item)@include('quotes.partials.item', ['index' => $index, 'item' => $item])@endforeach</div></section>
<label class="notes-label">Condições de pagamento<textarea name="payment_terms" rows="2" placeholder="Ex.: 50% de entrada e saldo na entrega.">{{ old('payment_terms', $quote->payment_terms) }}</textarea></label><label class="notes-label">Observações para o cliente<textarea name="notes" rows="4" placeholder="Condições, prazo ou detalhes de produção.">{{ old('notes', $quote->notes) }}</textarea></label>
</div><aside class="panel quote-summary"><p class="eyebrow">RESUMO FINANCEIRO</p><div><span>Subtotal</span><b id="subtotalPreview">R$ 0,00</b></div><label>Desconto (R$)<input id="discount" type="number" step="0.01" min="0" name="discount" value="{{ old('discount', $quote->discount ?? 0) }}"></label><div><span>Custo estimado</span><b id="costPreview">R$ 0,00</b></div><div><span>Preço sugerido</span><b id="suggestedPreview">R$ {{ number_format($quote->suggested_total ?? 0, 2, ',', '.') }}</b></div><button class="secondary full quote-apply-price" type="button" id="applySuggested">Aplicar preço sugerido aos itens</button><small class="quote-price-note" id="suggestedNote">O total proposto muda ao aplicar.</small><div class="quote-total"><span>Total proposto</span><strong id="totalPreview">R$ 0,00</strong></div><div class="margin-box"><span>Margem estimada</span><b id="marginPreview">—</b><small id="marginNote">Alerta abaixo de 20%</small></div><button class="primary full" type="submit">Salvar rascunho →</button></aside></div></form>
@if($quote->exists)<section class="panel quote-send-panel"><div><p class="eyebrow">REVISÃO E PUBLICAÇÃO</p><h2>Pronto para apresentar ao cliente?</h2><p>Salve todas as alterações antes de publicar. A versão ficará bloqueada e você poderá compartilhar o link com o cliente.</p></div><form method="POST" action="{{ route('orcamentos.send', $quote) }}">@csrf<button class="primary">Publicar V{{ $quote->version }} e gerar link →</button></form></section>@endif
@if($quote->exists)@include('quotes.attachments', ['readonly' => false])@endif
<template id="quoteItemTemplate">@include('quotes.partials.item', ['index' => '__INDEX__', 'item' => ['kind' => 'custom', 'quantity' => 1, 'unit_price' => 0, 'unit_cost' => 0]])</template>
<script src="{{ asset('js/quote-form.js') }}?v={{ filemtime(public_path('js/quote-form.js')) }}" defer></script>
@endsection
