<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><style>
@page { margin: 30px; } body { font: 12px DejaVu Sans, sans-serif; color:#183128; } .header { border-bottom:3px solid #bd8a15; padding:5px 0 15px; } .brand-logo { width:108px; height:72px; } .subtitle { color:#365247; margin-top:5px; } h2 { color:#173127; margin:25px 0 10px; font-size:17px; } .meta { width:100%; margin:18px 0; } .meta td { width:33%; padding:8px; border:1px solid #d9dfda; } .label { color:#64756c; font-size:9px; text-transform:uppercase; } table { width:100%; border-collapse:collapse; } th { background:#edf1ee; text-align:left; padding:9px; font-size:9px; color:#506158; } td { padding:10px 9px; border-bottom:1px solid #e0e5e1; } .right { text-align:right; } .total { margin-top:12px; text-align:right; font-size:16px; font-weight:bold; } .box { border:1px solid #d9dfda; padding:13px; margin-top:10px; } .footer { position:fixed; bottom:0; left:0; right:0; text-align:center; color:#64756c; font-size:9px; }
</style></head><body>
<div class="header"><img class="brand-logo" src="data:image/png;base64,{{ base64_encode(file_get_contents(public_path('images/alfarei-logo.png'))) }}" alt="Alfarei"><div class="subtitle">CNC · OPERAÇÃO &nbsp; | &nbsp; PROPOSTA COMERCIAL {{ $quote->number }} · V{{ $quote->version }}</div></div>
<table class="meta"><tr><td><div class="label">Cliente</div><strong>{{ $quote->customer->name }}</strong></td><td><div class="label">Emitida em</div><strong>{{ $quote->created_at->format('d/m/Y') }}</strong></td><td><div class="label">Validade</div><strong>{{ $quote->valid_until?->format('d/m/Y') ?? 'Não informada' }}</strong></td></tr></table>
<h2>Itens da proposta</h2><table><thead><tr><th>DESCRIÇÃO</th><th>QTD.</th><th class="right">VALOR UNIT.</th><th class="right">TOTAL</th></tr></thead><tbody>@foreach($quote->items as $item)<tr><td><strong>{{ $item->description }}</strong><br><small>{{ $item->type === 'product' ? 'Produto' : 'Serviço personalizado' }}</small></td><td>{{ number_format($item->quantity, 3, ',', '.') }}</td><td class="right">R$ {{ number_format($item->unit_price, 2, ',', '.') }}</td><td class="right">R$ {{ number_format($item->total, 2, ',', '.') }}</td></tr>@endforeach</tbody></table><div class="total">VALOR TOTAL: R$ {{ number_format($quote->total, 2, ',', '.') }}</div>
<h2>Condições comerciais</h2><div class="box"><strong>Entrada:</strong> {{ number_format($quote->deposit_percent, 0, ',', '.') }}% &nbsp;&nbsp;&nbsp; <strong>Prazo de produção:</strong> {{ $quote->production_lead_days ? $quote->production_lead_days.' dias úteis' : 'A combinar' }} &nbsp;&nbsp;&nbsp; <strong>Entrega/despacho:</strong> {{ $quote->delivery_lead_days ? $quote->delivery_lead_days.' dias úteis após a produção' : 'A combinar' }}<br><br>{!! nl2br(e($quote->payment_terms ?: 'Condições de pagamento a combinar com a equipe comercial.')) !!}</div>
@if($quote->notes)<h2>Observações</h2><div class="box">{!! nl2br(e($quote->notes)) !!}</div>@endif
<div class="footer">Alfarei CNC · Proposta {{ $quote->number }} · Documento gerado em {{ now()->format('d/m/Y H:i') }}</div>
</body></html>
