@extends('layouts.app', ['title' => 'Ficha técnica · Alfarei CNC'])
@section('content')
<div class="heading"><div><p class="eyebrow">CADASTROS · PRODUTOS</p><h1>Ficha técnica</h1><p class="muted">Materiais e operações por unidade de <b>{{ $product->name }}</b>. O custo é atualizado automaticamente.</p></div><a class="secondary" href="{{ route('produtos.index') }}">← Voltar aos itens</a></div>
<form class="panel form-card technical-sheet" method="POST" action="{{ route('produtos.technical-sheet.update', $product) }}">@csrf @method('PUT')
    <div class="form-section"><h2>Composição de materiais</h2><p class="muted">A perda prevista é adicionada à quantidade necessária e também entra na reserva de estoque.</p></div>
    @error('materials')<p class="field-error">{{ $message }}</p>@enderror @error('stock')<p class="field-error">{{ $message }}</p>@enderror
    <div id="bom-lines">
        @forelse(old('materials', $product->materials->map(fn($material) => ['material_id' => $material->id, 'quantity' => $material->pivot->quantity, 'loss_percent' => $material->pivot->loss_percent])->all()) as $index => $line)
            <div class="bom-line"><label>Material<select name="materials[{{ $index }}][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}" @selected((string)($line['material_id'] ?? '') === (string)$material->id)>{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[{{ $index }}][quantity]" type="number" min="0.001" step="0.001" value="{{ $line['quantity'] ?? '' }}" required></label><label>Perda prevista (%)<input name="materials[{{ $index }}][loss_percent]" type="number" min="0" max="100" step="0.01" value="{{ $line['loss_percent'] ?? 0 }}" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div>
        @empty
            <div class="bom-line"><label>Material<select name="materials[0][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[0][quantity]" type="number" min="0.001" step="0.001" required></label><label>Perda prevista (%)<input name="materials[0][loss_percent]" type="number" min="0" max="100" step="0.01" value="0" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div>
        @endforelse
    </div>
    <template id="bom-template"><div class="bom-line"><label>Material<select name="materials[__INDEX__][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[__INDEX__][quantity]" type="number" min="0.001" step="0.001" required></label><label>Perda prevista (%)<input name="materials[__INDEX__][loss_percent]" type="number" min="0" max="100" step="0.01" value="0" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div></template>
    <div class="form-section"><h2>Operações e custo-hora</h2><p class="muted">Informe o tempo necessário por unidade. O sistema utiliza automaticamente o custo/hora atual de cada máquina.</p></div>
    <div id="operation-lines">
        @forelse(old('operations', $product->machineOperations->map(fn($machine) => ['machine_id' => $machine->id, 'operation_name' => $machine->pivot->operation_name, 'minutes_per_unit' => $machine->pivot->minutes_per_unit, 'setup_minutes' => $machine->pivot->setup_minutes])->all()) as $index => $line)
            <div class="bom-line"><label>Máquina<select name="operations[{{ $index }}][machine_id]" required><option value="">Selecione</option>@foreach($machines as $machine)<option value="{{ $machine->id }}" @selected((string)($line['machine_id'] ?? '') === (string)$machine->id)>{{ $machine->name }} · R$ {{ number_format($machine->calculatedHourlyCost(), 2, ',', '.') }}/h</option>@endforeach</select></label><label>Operação<input name="operations[{{ $index }}][operation_name]" value="{{ $line['operation_name'] ?? '' }}" placeholder="Ex.: corte CNC" required></label><label>Minutos/unidade<input name="operations[{{ $index }}][minutes_per_unit]" type="number" min="0.01" step="0.01" value="{{ $line['minutes_per_unit'] ?? '' }}" required></label><label>Setup (min.)<input name="operations[{{ $index }}][setup_minutes]" type="number" min="0" step="0.01" value="{{ $line['setup_minutes'] ?? 0 }}" required></label><button class="remove-operation" type="button" aria-label="Remover operação">×</button></div>
        @empty
            <div class="bom-line"><label>Máquina<select name="operations[0][machine_id]" required><option value="">Selecione</option>@foreach($machines as $machine)<option value="{{ $machine->id }}">{{ $machine->name }} · R$ {{ number_format($machine->calculatedHourlyCost(), 2, ',', '.') }}/h</option>@endforeach</select></label><label>Operação<input name="operations[0][operation_name]" placeholder="Ex.: corte CNC" required></label><label>Minutos/unidade<input name="operations[0][minutes_per_unit]" type="number" min="0.01" step="0.01" required></label><label>Setup (min.)<input name="operations[0][setup_minutes]" type="number" min="0" step="0.01" value="0" required></label><button class="remove-operation" type="button" aria-label="Remover operação">×</button></div>
        @endforelse
    </div>
    <template id="operation-template"><div class="bom-line"><label>Máquina<select name="operations[__INDEX__][machine_id]" required><option value="">Selecione</option>@foreach($machines as $machine)<option value="{{ $machine->id }}">{{ $machine->name }} · R$ {{ number_format($machine->calculatedHourlyCost(), 2, ',', '.') }}/h</option>@endforeach</select></label><label>Operação<input name="operations[__INDEX__][operation_name]" placeholder="Ex.: corte CNC" required></label><label>Minutos/unidade<input name="operations[__INDEX__][minutes_per_unit]" type="number" min="0.01" step="0.01" required></label><label>Setup (min.)<input name="operations[__INDEX__][setup_minutes]" type="number" min="0" step="0.01" value="0" required></label><button class="remove-operation" type="button" aria-label="Remover operação">×</button></div></template>
    <div class="form-actions"><button class="secondary" id="add-bom" type="button">＋ Adicionar material</button><button class="secondary" id="add-operation" type="button">＋ Adicionar operação</button><button class="primary" type="submit">Salvar ficha técnica →</button></div>
</form>
<script>const lines=document.getElementById('bom-lines'),template=document.getElementById('bom-template'),operations=document.getElementById('operation-lines'),operationTemplate=document.getElementById('operation-template');let index=lines.children.length,operationIndex=operations.children.length;document.getElementById('add-bom').addEventListener('click',()=>{lines.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index++));});document.getElementById('add-operation').addEventListener('click',()=>{operations.insertAdjacentHTML('beforeend',operationTemplate.innerHTML.replaceAll('__INDEX__',operationIndex++));});lines.addEventListener('click',event=>{if(event.target.classList.contains('remove-bom')&&lines.children.length>1)event.target.closest('.bom-line').remove();});operations.addEventListener('click',event=>{if(event.target.classList.contains('remove-operation')&&operations.children.length>1)event.target.closest('.bom-line').remove();});</script>
@endsection
