@extends('layouts.app', ['title' => 'Ficha técnica · Alfarei CNC'])
@section('content')
<div class="heading"><div><p class="eyebrow">CADASTROS · PRODUTOS</p><h1>Ficha técnica</h1><p class="muted">Defina os materiais consumidos por unidade de <b>{{ $product->name }}</b>. A reserva é automática ao liberar a OP.</p></div><a class="secondary" href="{{ route('produtos.index') }}">← Voltar aos itens</a></div>
<form class="panel form-card technical-sheet" method="POST" action="{{ route('produtos.technical-sheet.update', $product) }}">@csrf @method('PUT')
    <div class="form-section"><h2>Composição de materiais</h2><p class="muted">A perda prevista é adicionada à quantidade necessária e também entra na reserva de estoque.</p></div>
    @error('materials')<p class="field-error">{{ $message }}</p>@enderror @error('stock')<p class="field-error">{{ $message }}</p>@enderror
    <div id="bom-lines">
        @forelse(old('materials', $product->materials->map(fn($material) => ['material_id' => $material->id, 'quantity' => $material->pivot->quantity, 'loss_percent' => $material->pivot->loss_percent])->all()) as $index => $line)
            <div class="bom-line"><label>Material<select name="materials[{{ $index }}][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}" @selected((string)($line['material_id'] ?? '') === (string)$material->id)>{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[{{ $index }}][quantity]" type="number" min="0.001" step="0.001" value="{{ $line['quantity'] ?? '' }}" required></label><label>Perda prevista (%)<input name="materials[{{ $index }}][loss_percent]" type="number" min="0" max="100" step="0.01" value="{{ $line['loss_percent'] ?? 0 }}" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div>
        @empty
            <div class="bom-line"><label>Material<select name="materials[0][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[0][quantity]" type="number" min="0.001" step="0.001" required></label><label>Perda prevista (%)<input name="materials[0][loss_percent]" type="number" min="0" max="100" step="0.01" value="0" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div>
        @endforelse
    </div>
    <template id="bom-template"><div class="bom-line"><label>Material<select name="materials[__INDEX__][material_id]" required><option value="">Selecione</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} · {{ $material->name }} (disp.: {{ number_format((float)$material->stock_quantity - (float)$material->reserved_quantity, 3, ',', '.') }} {{ $material->unit }})</option>@endforeach</select></label><label>Qtd. por unidade<input name="materials[__INDEX__][quantity]" type="number" min="0.001" step="0.001" required></label><label>Perda prevista (%)<input name="materials[__INDEX__][loss_percent]" type="number" min="0" max="100" step="0.01" value="0" required></label><button class="remove-bom" type="button" aria-label="Remover material">×</button></div></template>
    <div class="form-actions"><button class="secondary" id="add-bom" type="button">＋ Adicionar material</button><button class="primary" type="submit">Salvar ficha técnica →</button></div>
</form>
<script>const lines=document.getElementById('bom-lines'),template=document.getElementById('bom-template');let index=lines.children.length;document.getElementById('add-bom').addEventListener('click',()=>{lines.insertAdjacentHTML('beforeend',template.innerHTML.replaceAll('__INDEX__',index++));});lines.addEventListener('click',event=>{if(event.target.classList.contains('remove-bom')&&lines.children.length>1)event.target.closest('.bom-line').remove();});</script>
@endsection
