@extends('layouts.app', ['title' => 'Configurar loja · Alfarei CNC'])

@section('content')
<div class="heading"><div><p class="eyebrow">E-COMMERCE · ADMINISTRAÇÃO</p><h1>Configurar loja virtual</h1><p class="muted">Toda a comunicação, regras e aparência da loja em um só lugar.</p></div><a class="secondary" target="_blank" href="{{ route('loja.index') }}">Visualizar loja ↗</a></div>
<form class="store-settings-form" method="POST" action="{{ route('loja.settings.update') }}">@csrf @method('PUT')
    <section class="panel settings-section"><div class="settings-head"><div><span>01</span><h2>Marca e vitrine</h2></div><p>Defina a primeira impressão que o cliente terá ao entrar na loja.</p></div><div class="form-grid"><label>Nome da loja<input name="store_name" value="{{ old('store_name', $settings->store_name) }}" required></label><label>Título principal<input name="hero_title" value="{{ old('hero_title', $settings->hero_title) }}" required></label><label class="span-2">Texto de apresentação<textarea name="hero_subtitle" rows="3">{{ old('hero_subtitle', $settings->hero_subtitle) }}</textarea></label><label>Texto do botão principal<input name="hero_cta_label" value="{{ old('hero_cta_label', $settings->hero_cta_label ?: 'Ver produtos') }}" required></label><label>Destino do botão <small>(opcional)</small><input name="hero_cta_url" value="{{ old('hero_cta_url', $settings->hero_cta_url) }}" placeholder="#catalogo ou https://..."></label><label class="span-2">Imagem de fundo do banner <small>(URL opcional)</small><input type="url" name="hero_image_url" value="{{ old('hero_image_url', $settings->hero_image_url) }}" placeholder="https://..."></label></div><div class="settings-toggles"><label><input type="hidden" name="announcement_active" value="0"><input type="checkbox" name="announcement_active" value="1" @checked(old('announcement_active', $settings->announcement_active))> Exibir faixa de aviso no topo</label><label class="wide">Texto do aviso<input name="announcement_text" value="{{ old('announcement_text', $settings->announcement_text) }}" placeholder="Ex.: Frete grátis em Cuiabá acima de R$ 200"></label></div></section>

    <section class="panel settings-section"><div class="settings-head"><div><span>02</span><h2>Cores e identidade visual</h2></div><p>As cores são aplicadas automaticamente nos botões, banner e destaques da loja.</p></div><div class="color-settings"><label>Cor principal<input type="color" name="primary_color" value="{{ old('primary_color', $settings->primary_color ?: '#193128') }}"><code>{{ old('primary_color', $settings->primary_color ?: '#193128') }}</code></label><label>Cor de destaque<input type="color" name="accent_color" value="{{ old('accent_color', $settings->accent_color ?: '#d1a943') }}"><code>{{ old('accent_color', $settings->accent_color ?: '#d1a943') }}</code></label></div></section>

    <section class="panel settings-section"><div class="settings-head"><div><span>03</span><h2>Atendimento e presença digital</h2></div><p>Informações exibidas no rodapé e usadas para facilitar o contato.</p></div><div class="form-grid"><label>WhatsApp<input name="whatsapp" value="{{ old('whatsapp', $settings->whatsapp) }}" placeholder="(65) 99999-9999"></label><label>E-mail de suporte<input type="email" name="support_email" value="{{ old('support_email', $settings->support_email) }}"></label><label class="span-2">Mensagem inicial do WhatsApp<textarea name="whatsapp_message" rows="2" placeholder="Olá! Vim pela loja virtual e quero tirar uma dúvida.">{{ old('whatsapp_message', $settings->whatsapp_message) }}</textarea></label><label>Instagram<input type="url" name="instagram_url" value="{{ old('instagram_url', $settings->instagram_url) }}" placeholder="https://instagram.com/... "></label><label>Facebook<input type="url" name="facebook_url" value="{{ old('facebook_url', $settings->facebook_url) }}" placeholder="https://facebook.com/... "></label><label>Endereço / local de retirada<input name="address" value="{{ old('address', $settings->address) }}"></label><label>Horário de atendimento<input name="business_hours" value="{{ old('business_hours', $settings->business_hours) }}" placeholder="Seg. a sex., 8h às 18h"></label></div></section>

    <section class="panel settings-section"><div class="settings-head"><div><span>04</span><h2>Entrega, retirada e produção</h2></div><p>Defina como o cliente recebe o pedido e quais mensagens aparecem no checkout.</p></div><div class="settings-toggles two"><label><input type="hidden" name="pickup_enabled" value="0"><input type="checkbox" name="pickup_enabled" value="1" @checked(old('pickup_enabled', $settings->pickup_enabled))> Permitir retirada</label><label><input type="hidden" name="shipping_enabled" value="0"><input type="checkbox" name="shipping_enabled" value="1" @checked(old('shipping_enabled', $settings->shipping_enabled))> Permitir entrega</label></div><div class="form-grid"><label class="span-2">Endereço para retirada<input name="pickup_address" value="{{ old('pickup_address', $settings->pickup_address) }}"></label><label>Prazo padrão de produção (dias)<input type="number" min="0" name="production_days" value="{{ old('production_days', $settings->production_days) }}"></label><label>Frete grátis acima de (R$)<input type="number" step="0.01" min="0" name="free_shipping_minimum" value="{{ old('free_shipping_minimum', $settings->free_shipping_minimum) }}"></label><label class="span-2">Mensagem de entrega<input name="shipping_message" value="{{ old('shipping_message', $settings->shipping_message) }}" placeholder="Frete confirmado pela equipe após o pedido."></label><label class="span-2">Mensagem de produção / entrega<input name="delivery_message" value="{{ old('delivery_message', $settings->delivery_message) }}"></label></div></section>

    <section class="panel settings-section"><div class="settings-head"><div><span>05</span><h2>Pagamento</h2></div><p>Ative os meios disponíveis. Credenciais do Mercado Pago serão configuradas de forma segura em uma etapa própria.</p></div><div class="settings-toggles three"><label><input type="hidden" name="pix_enabled" value="0"><input type="checkbox" name="pix_enabled" value="1" @checked(old('pix_enabled', $settings->pix_enabled))> Aceitar PIX</label><label><input type="hidden" name="mercado_pago_enabled" value="0"><input type="checkbox" name="mercado_pago_enabled" value="1" @checked(old('mercado_pago_enabled', $settings->mercado_pago_enabled))> Mercado Pago</label><label><input type="hidden" name="card_enabled" value="0"><input type="checkbox" name="card_enabled" value="1" @checked(old('card_enabled', $settings->card_enabled))> Cartão</label></div><div class="form-grid"><label>Chave PIX<input name="pix_key" value="{{ old('pix_key', $settings->pix_key) }}"></label><label>Entrada exigida (%)<input type="number" step="0.01" min="0" max="100" name="deposit_percent" value="{{ old('deposit_percent', $settings->deposit_percent ?? 50) }}" required></label></div></section>

    <details class="panel settings-section advanced-settings"><summary>SEO, compartilhamento e métricas</summary><div class="form-grid"><label>SEO: título da página<input name="seo_title" value="{{ old('seo_title', $settings->seo_title) }}"></label><label>Imagem para compartilhamento<input type="url" name="share_image_url" value="{{ old('share_image_url', $settings->share_image_url) }}" placeholder="https://..."></label><label class="span-2">SEO: descrição<textarea name="seo_description" rows="2">{{ old('seo_description', $settings->seo_description) }}</textarea></label><label>Google Analytics (ID)<input name="google_analytics_id" value="{{ old('google_analytics_id', $settings->google_analytics_id) }}" placeholder="G-XXXXXXXXXX"></label><label>Meta Pixel (ID)<input name="meta_pixel_id" value="{{ old('meta_pixel_id', $settings->meta_pixel_id) }}"></label><label class="span-2">Política de privacidade<textarea name="privacy_policy" rows="4">{{ old('privacy_policy', $settings->privacy_policy) }}</textarea></label><label class="span-2">Política de trocas e devoluções<textarea name="return_policy" rows="4">{{ old('return_policy', $settings->return_policy) }}</textarea></label></div></details>
    <div class="store-settings-save"><label><input type="hidden" name="store_open" value="0"><input type="checkbox" name="store_open" value="1" @checked(old('store_open', $settings->store_open))> Loja aberta para receber pedidos</label><button class="primary" type="submit">Salvar e publicar configurações →</button></div>
</form>
@endsection
